# Dockerfile

# Start with the official Golang image
FROM golang:1.21-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o /budgello-app

# Start a new, smaller stage from scratch
FROM alpine:latest

# Set the working directory
WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /budgello-app .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./budgello-app"]